name: Deploy to server

on:
  workflow_dispatch:
  push:
    branches:
      - gfournier

permissions:
  contents: read

job:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout
      