name: Deploy to server

on:
  workflow_dispatch:
  push:
    branches:
      - gfournier

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install SCP
        run: sudo apt-get install -y scp
      - name: SCP
        run: scp *.html gfournier.ca:/var/www/html/gfournier/

      